-- QueueKisan queue-system migration
-- Safe additive migration for realtime queue orchestration and ML-ready analytics.

alter table public.queue_tokens
  add column if not exists booked_at timestamptz,
  add column if not exists checked_in_at timestamptz,
  add column if not exists called_at timestamptz,
  add column if not exists service_started_at timestamptz,
  add column if not exists service_completed_at timestamptz,
  add column if not exists skipped_at timestamptz,
  add column if not exists rejoined_at timestamptz,
  add column if not exists no_show_at timestamptz,
  add column if not exists estimated_wait_minutes numeric,
  add column if not exists priority_score numeric not null default 0,
  add column if not exists notification_stage text not null default 'none',
  add column if not exists last_event_at timestamptz not null default now(),
  add column if not exists last_prediction_source text not null default 'historical-heuristic';

update public.queue_tokens
set booked_at = coalesce(booked_at, created_at, now()),
    estimated_wait_minutes = coalesce(
      estimated_wait_minutes,
      nullif(regexp_replace(coalesce(estimated_wait_time, ''), '[^0-9.]', '', 'g'), '')::numeric
    ),
    last_event_at = coalesce(last_event_at, created_at, now())
where booked_at is null
   or estimated_wait_minutes is null
   or last_event_at is null;

create table if not exists public.queue_events (
  id bigint generated by default as identity primary key,
  token_id text not null references public.queue_tokens(id) on delete cascade,
  farmer_id text,
  centre_id text,
  counter_id text,
  event_type text not null,
  old_status text,
  new_status text,
  queue_position integer,
  estimated_wait_minutes numeric,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_queue_events_token_id on public.queue_events(token_id);
create index if not exists idx_queue_events_centre_id on public.queue_events(centre_id);
create index if not exists idx_queue_events_created_at on public.queue_events(created_at desc);

create table if not exists public.queue_token_counters (
  centre_id text not null,
  queue_date date not null,
  last_number integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (centre_id, queue_date)
);

insert into public.queue_token_counters (centre_id, queue_date, last_number)
select
  qt.centre_id,
  qt.slot_date,
  max(coalesce(nullif(regexp_replace(qt.token_number, '[^0-9]', '', 'g'), ''), '0')::integer) as last_number
from public.queue_tokens qt
group by qt.centre_id, qt.slot_date
on conflict (centre_id, queue_date) do update
set last_number = greatest(public.queue_token_counters.last_number, excluded.last_number),
    updated_at = now();

create or replace function public.next_queue_token(p_centre_id text, p_queue_date date)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  next_number integer;
begin
  insert into public.queue_token_counters (centre_id, queue_date, last_number, updated_at)
  values (p_centre_id, p_queue_date, 1, now())
  on conflict (centre_id, queue_date)
  do update
    set last_number = public.queue_token_counters.last_number + 1,
        updated_at = now()
  returning last_number into next_number;

  return 'T-' || lpad(next_number::text, 3, '0');
end;
$$;

grant select, insert, update, delete on table public.queue_events to anon, authenticated, service_role;
grant select on table public.queue_token_counters to anon, authenticated, service_role;
grant insert, update, delete on table public.queue_token_counters to service_role;
grant execute on function public.next_queue_token(text, date) to anon, authenticated, service_role;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'queue_events_id_seq'
  ) then
    execute 'grant usage, select on sequence public.queue_events_id_seq to anon, authenticated, service_role';
  end if;
end $$;

alter table public.queue_events enable row level security;
alter table public.queue_token_counters enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'queue_events' and policyname = 'Public app can read queue events'
  ) then
    create policy "Public app can read queue events"
      on public.queue_events
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'queue_events' and policyname = 'Service app can insert queue events'
  ) then
    create policy "Service app can insert queue events"
      on public.queue_events
      for insert
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'queue_token_counters' and policyname = 'Public app can read queue token counters'
  ) then
    create policy "Public app can read queue token counters"
      on public.queue_token_counters
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'queue_token_counters' and policyname = 'Service app can manage queue token counters'
  ) then
    create policy "Service app can manage queue token counters"
      on public.queue_token_counters
      for all
      using (true)
      with check (true);
  end if;
end $$;
