import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

// Translation files
const translations = {
  en: {
    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.queue': 'Queue Monitoring',
    'nav.farmers': 'Farmers',
    'nav.procurement': 'Procurement',
    'nav.payments': 'Payments',
    'nav.centres': 'Centres & Slots',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.operations': 'OPERATIONS',
    'nav.collapse': 'Collapse',

    // Header & Search
    'header.search': 'Search farmers, tokens...',
    'header.settings': 'Settings',
    'header.notifications': 'Notifications',
    'header.logout': 'Logout',

    // Dashboard
    'dashboard.title': 'Operations Dashboard',
    'dashboard.subtitle': 'Real-time overview of procurement-centre activity',
    'dashboard.overview': 'System Overview',
    'dashboard.overview.subtitle': 'QueueKisan real-time operational metrics',
    'dashboard.totalFarmers': 'TOTAL FARMERS TODAY',
    'dashboard.waiting': 'WAITING',
    'dashboard.serving': 'CURRENTLY SERVING',
    'dashboard.completed': 'COMPLETED PROCUREMENTS',
    'dashboard.pendingPayments': 'PENDING PAYMENTS',
    'dashboard.totalAmount': 'Total Amount (₹)',
    'dashboard.capacityUtilization': 'Centre Capacity Utilization',
    'dashboard.liveQueue': 'Live Queue Overview',
    'dashboard.live': 'Live',
    'dashboard.currentToken': 'Current Token',
    'dashboard.centre': 'Centre',
    'dashboard.waitingCol': 'Waiting',
    'dashboard.estWait': 'Est. Wait',
    'dashboard.quickActions': 'Quick Actions',

    // Button Labels
    'btn.login': 'Login',
    'btn.logout': 'Logout',
    'btn.signup': 'Sign Up',
    'btn.back': '← Back to Role Selection',
    'btn.search': 'Search',
    'btn.filter': 'Filter',
    'btn.export': 'Export',
    'btn.manageCentres': 'Manage Centres',
    'btn.manageCentres.desc': 'Add or edit procurement centres',
    'btn.manageSlots': 'Manage Slots',
    'btn.manageSlots.desc': 'Configure capacity and dates',
    'btn.queueMonitor': 'Queue Monitor',
    'btn.queueMonitor.desc': 'View real-time token status',
    'btn.viewAnalytics': 'View Analytics',
    'btn.viewAnalytics.desc': 'Check AI predictions & trends',

    // Status Labels
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.processing': 'Processing',
    'status.completed': 'Completed',
    'status.pending': 'Pending',
    'status.failed': 'Failed',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.language': 'Language',
    'common.english': 'English',
    'common.marathi': 'मराठी',
    'common.hindi': 'हिन्दी',

    // Auth
    'auth.adminLogin': 'Admin Login',
    'auth.createAccount': 'Create Admin Account',
    'auth.signInDesc': 'Sign in to manage system operations',
    'auth.signUpDesc': 'Sign in with an existing administrator account',
    'auth.username': 'Username / Admin Name',
    'auth.usernamePlaceholder': 'Enter your admin name',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.adminId': 'Admin ID',
    'auth.adminIdPlaceholder': 'e.g. ADM-2024-001',
    'auth.branch': 'Branch',
    'auth.branchPlaceholder': 'e.g. Main Branch',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.createBtn': 'Sign In',
    'auth.needAccount': 'Use an existing administrator account',
    'auth.haveAccount': 'Administrator access required',
    'auth.helperText': 'Use an existing Admin ID such as usr-a001, usr-41033, or usr-31633 with its assigned password.',

    // Farmers Page
    'farmers.title': 'Farmer Monitoring',
    'farmers.subtitle': 'Manage and view farmer information across all centres',
    'farmers.searchPlaceholder': 'Search by name, ID, mobile, village...',
    'farmers.allStatuses': 'All Statuses',
    'farmers.active': 'Active',
    'farmers.inactive': 'Inactive',
    'farmers.total': 'Total',
    'farmers.farmers': 'farmers',
    'farmers.colId': 'Farmer ID',
    'farmers.colName': 'Farmer Name',
    'farmers.colMobile': 'Mobile',
    'farmers.colVillage': 'Village',
    'farmers.colBookings': 'Bookings',
    'farmers.colStatus': 'Status',
    'farmers.profile': 'Farmer Profile',
    'farmers.tabInfo': 'Information',
    'farmers.tabBookings': 'Booking History',
    'farmers.tabProcurements': 'Procurements',
    'farmers.tabPayments': 'Payments',
    'farmers.farmerId': 'Farmer ID',
    'farmers.mobileNumber': 'Mobile Number',
    'farmers.aadhaar': 'Aadhaar',
    'farmers.locationDetails': 'Location Details',
    'farmers.village': 'Village',
    'farmers.talukaDistrict': 'Taluka / District',
    'farmers.registrationDate': 'Registration Date',
    'farmers.bookingId': 'Booking ID',
    'farmers.centre': 'Centre',
    'farmers.date': 'Date',
    'farmers.time': 'Time',
    'farmers.crop': 'Crop',
    'farmers.id': 'ID',
    'farmers.qty': 'Qty',
    'farmers.amount': 'Amount (₹)',
    'farmers.refId': 'Ref ID',
    'farmers.procId': 'Proc. ID',

    // Procurement Page
    'procurement.title': 'Procurement Monitoring',
    'procurement.subtitle': 'Track crop procurement across all active centres',
    'procurement.allCentres': 'All Centres',
    'procurement.allCrops': 'All Crops',
    'procurement.allStatuses': 'All Statuses',
    'procurement.completed': 'Completed',
    'procurement.processing': 'Processing',
    'procurement.pending': 'Pending',
    'procurement.exportData': 'Export Data',
    'procurement.colId': 'Procurement ID',
    'procurement.colDate': 'Date',
    'procurement.colCentre': 'Centre',
    'procurement.colFarmer': 'Farmer',
    'procurement.colCrop': 'Crop',
    'procurement.colQty': 'Qty',
    'procurement.colGrade': 'Grade',
    'procurement.colAmount': 'Amount',
    'procurement.colStatus': 'Status',

    // Payments Page
    'payments.title': 'Payment Monitoring',
    'payments.subtitle': 'Track payment status and settlement progress',
    'payments.totalAmount': 'Total Amount',
    'payments.completedPayments': 'Completed Payments',
    'payments.pendingPayments': 'Pending Payments',
    'payments.allCentres': 'All Centres',
    'payments.allStatuses': 'All Statuses',
    'payments.completed': 'Completed',
    'payments.pending': 'Pending',
    'payments.failed': 'Failed',
    'payments.colRefId': 'Payment Ref ID',
    'payments.colFarmer': 'Farmer',
    'payments.colProcId': 'Proc. ID',
    'payments.colCentre': 'Centre',
    'payments.colAmount': 'Amount',
    'payments.colMethod': 'Method',
    'payments.colDate': 'Date',
    'payments.colStatus': 'Status',

    // Centres & Slots
    'centres.title': 'Centres, Slots & Officers',
    'centres.subtitle': 'Manage procurement locations, timing capacity, and assigned personnel',
    'centres.tabCentres': 'Centres',
    'centres.tabSlots': 'Slot & Capacity Config',
    'centres.tabOfficers': 'Officers',
    'centres.addCentre': 'Add Centre',
    'centres.createSlots': 'Create Slots',
    'centres.assignOfficer': 'Assign Officer',
    'centres.selectCentre': 'Select Centre',
    'centres.filterByCentre': 'Filter by Centre',
    'centres.colCentreId': 'Centre ID',
    'centres.colName': 'Centre Name',
    'centres.colTaluka': 'Taluka',
    'centres.colCapacity': 'Total Capacity',
    'centres.colCurrentLoad': 'Current Load',
    'centres.colStatus': 'Status',
    'centres.colActions': 'Actions',
    'centres.colDate': 'Date',
    'centres.colTimeSlot': 'Time Slot',
    'centres.colSlotCapacity': 'Capacity',
    'centres.colBooked': 'Booked',
    'centres.colRemaining': 'Remaining',
    'centres.colOfficerId': 'Officer ID',
    'centres.colOfficerName': 'Name',
    'centres.colRole': 'Role',
    'centres.colMobile': 'Mobile',
    'centres.colAssignedCentre': 'Assigned Centre',
    'centres.officerNote': 'Note: Officers manage queues from their dedicated application. Admins can view and assign them here.',
    'centres.modalAddCentre': 'Add New Centre',
    'centres.modalEditCentre': 'Edit Procurement Centre',
    'centres.modalConfigSlots': 'Configure Slots & Capacity',
    'centres.btnCancel': 'Cancel',
    'centres.btnSaveCentre': 'Save Centre',
    'centres.btnGenerateSlots': 'Generate Slots',
    'centres.lblCentreName': 'Centre Name',
    'centres.lblTaluka': 'Taluka',
    'centres.lblDistrict': 'District',
    'centres.lblAddress': 'Address',
    'centres.lblBaseCapacity': 'Base Capacity (per hour)',
    'centres.lblStatus': 'Status',
    'centres.lblStartDate': 'Start Date',
    'centres.lblEndDate': 'End Date',
    'centres.lblTimeRange': 'Time Range',
    'centres.lblSlotDuration': 'Slot Duration (Minutes)',
    'centres.lblCapacityPerSlot': 'Capacity per Slot',
    'centres.placeholderCentreName': 'e.g., Kopargaon APMC Centre',
    'centres.capacityNote': 'The system will strictly prevent bookings beyond this configured capacity.',
    'centres.min30': '30 Minutes',
    'centres.min60': '60 Minutes (1 Hour)',
    'centres.to': 'to',

    // queue
    'queue.title': 'Live Queue Monitoring',
    'queue.subtitle': 'Centralized view of real-time queues across all procurement centres',
    'queue.liveUpdates': 'Live Updates Active',
    'queue.centreId': 'Centre ID',
    'queue.currentToken': 'Current Token',
    'queue.serving': 'Serving',
    'queue.waitingFarmers': 'Waiting Farmers',
    'queue.highLoadAlert': 'High Load Alert',
    'queue.estWaitTime': 'Est. Waiting Time',
    'queue.tokensCompleted': 'Tokens Completed',
    'queue.bookedSlots': 'Booked Slots',
    'queue.bookings': 'bookings',
    'queue.token': 'Token',
    'queue.farmer': 'Farmer',
    'queue.crop': 'Crop',
    'queue.date': 'Date',
    'queue.slot': 'Slot',
    'queue.checkIn': 'Check-in',
    'queue.status': 'Status',
    'queue.noBookedSlots': 'No booked slots for this centre.',

    // analytics
    'analytics.title': 'System Analytics & Predictions',
    'analytics.subtitle': 'Data-driven insights, trends, and AI/ML forecasts',
    'analytics.aiPredictions': 'AI/ML Predictions',
    'analytics.predicted': 'Predicted',
    'analytics.expectedCrowd': 'Expected Crowd Level (Today)',
    'analytics.avgEstWait': 'Avg. Estimated Wait Time',
    'analytics.peakWindow': 'Peak Processing Window',
    'analytics.expectedNoShow': 'Expected No-Show Rate',
    'analytics.confidence': 'Confidence',
    'analytics.tabFarmer': 'Farmer Analytics',
    'analytics.tabProcurement': 'Procurement',
    'analytics.tabQueue': 'Queue & Centres',
    'analytics.farmerReg': 'Farmer Registrations (2025-2026)',
    'analytics.villageDist': 'Village Distribution',
    'analytics.dailyVol': 'Daily Procurement Volumes',
    'analytics.cropDist': 'Crop Distribution',
    'analytics.avgWait': 'Average Waiting Time Throughout Day',
    'analytics.centreCap': 'Centre Capacity Utilization (%)',
    'analytics.aiRecommendations': 'AI System Recommendations',
    'analytics.predictedLoad': 'Predicted Load',
    'analytics.lblRegistrations': 'Registrations',
    'analytics.lblFarmers': 'Farmers',
    'analytics.lblProcurementsCompleted': 'Procurements Completed',
    'analytics.lblWaitTime': 'Wait Time (mins)',
    'analytics.lblUtilization': 'Utilization %',

    // reports
    'reports.title': 'Reports & Exports',
    'reports.subtitle': 'Generate monthly summaries and export data for external use',
    'reports.monthlySummary': 'Monthly Summary Report',
    'reports.exportPdf': 'Export PDF',
    'reports.exportCsv': 'Export CSV',
    'reports.totalFarmers': 'Total Farmers Served',
    'reports.totalProcurement': 'Total Procurement',
    'reports.totalAmount': 'Total Amount',
    'reports.avgWaitTime': 'Avg Waiting Time',
    'reports.centrePerformance': 'Centre Performance Detail',
    'reports.colName': 'Centre Name',
    'reports.colCapacity': 'Capacity (ph)',
    'reports.colUtilization': 'Avg Utilization',
    'reports.colThroughput': 'Farmers Served',
    'reports.colWaitTime': 'Avg Wait Time',
  },
  mr: {
    // Sidebar
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.queue': 'रांग निरीक्षण',
    'nav.farmers': 'शेतकरी',
    'nav.procurement': 'खरेदी',
    'nav.payments': 'भुगतान',
    'nav.centres': 'केंद्रे आणि स्लॉट',
    'nav.analytics': 'विश्लेषण',
    'nav.reports': 'अहवाले',
    'nav.operations': 'ऑपरेशन',
    'nav.collapse': 'कंप्रेस करा',

    // Header & Search
    'header.search': 'शेतकरी, टोकन शोधा...',
    'header.settings': 'सेटिंग्ज',
    'header.notifications': 'सूचना',
    'header.logout': 'लॉगआउट',

    // Dashboard
    'dashboard.title': 'ऑपरेशन डॅशबोर्ड',
    'dashboard.subtitle': 'खरेदी-केंद्र क्रियाकलाप यांचा रीयल-टाइम विहंगावलोकन',
    'dashboard.overview': 'प्रणाली विहंगावलोकन',
    'dashboard.overview.subtitle': 'कृषीदर्पण रीयल-टाइम परिचालन मेट्रिक्स',
    'dashboard.totalFarmers': 'आज एकूण शेतकरी',
    'dashboard.waiting': 'प्रतीक्षेत',
    'dashboard.serving': 'सध्या सेवा देत आहे',
    'dashboard.completed': 'पूर्ण खरेदी',
    'dashboard.pendingPayments': 'प्रलंबित भुगतान',
    'dashboard.totalAmount': 'एकूण रक्कम (₹)',
    'dashboard.capacityUtilization': 'केंद्र क्षमता वापर',
    'dashboard.liveQueue': 'लाइव रांग विहंगावलोकन',
    'dashboard.live': 'लाइव',
    'dashboard.currentToken': 'वर्तमान टोकन',
    'dashboard.centre': 'केंद्र',
    'dashboard.waitingCol': 'प्रतीक्षेत',
    'dashboard.estWait': 'अनुमानित प्रतीक्षा',
    'dashboard.quickActions': 'त्वरित क्रिया',

    // Button Labels
    'btn.login': 'लॉगइन',
    'btn.logout': 'लॉगआउट',
    'btn.signup': 'साइन अप',
    'btn.back': '← भूमिका निवडीकडे परत',
    'btn.search': 'शोधा',
    'btn.filter': 'फिल्टर',
    'btn.export': 'निर्यात',
    'btn.manageCentres': 'केंद्रे व्यवस्थापित करा',
    'btn.manageCentres.desc': 'खरेदी केंद्रे जोडा किंवा संपादित करा',
    'btn.manageSlots': 'स्लॉट व्यवस्थापित करा',
    'btn.manageSlots.desc': 'क्षमता आणि तारीख कॉन्फिगर करा',
    'btn.queueMonitor': 'रांग मॉनिटर',
    'btn.queueMonitor.desc': 'रीयल-टाइम टोकन स्थिती पहा',
    'btn.viewAnalytics': 'विश्लेषण पहा',
    'btn.viewAnalytics.desc': 'AI भविष्यद्वाणी आणि ट्रेंड तपासा',

    // Status Labels
    'status.active': 'सक्रिय',
    'status.inactive': 'निष्क्रिय',
    'status.processing': 'प्रक्रियाधीन',
    'status.completed': 'पूर्ण',
    'status.pending': 'प्रलंबित',
    'status.failed': 'अयोग्य',

    // Common
    'common.loading': 'लोड करत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यश',
    'common.search': 'शोधा...',
    'common.filter': 'फिल्टर',
    'common.language': 'भाषा',
    'common.english': 'English',
    'common.marathi': 'मराठी',
    'common.hindi': 'हिन्दी',

    // Auth
    'auth.adminLogin': 'ॲडमिन लॉगइन',
    'auth.createAccount': 'ॲडमिन खाते तयार करा',
    'auth.signInDesc': 'सिस्टम ऑपरेशन्स व्यवस्थापित करण्यासाठी साइन इन करा',
    'auth.signUpDesc': 'विद्यमान प्रशासक खात्याने साइन इन करा',
    'auth.username': 'वापरकर्तानाव / ॲडमिन नाव',
    'auth.usernamePlaceholder': 'तुमचे ॲडमिन नाव प्रविष्ट करा',
    'auth.password': 'पासवर्ड',
    'auth.passwordPlaceholder': 'तुमचा पासवर्ड प्रविष्ट करा',
    'auth.adminId': 'ॲडमिन आयडी',
    'auth.adminIdPlaceholder': 'उदा. ADM-2024-001',
    'auth.branch': 'शाखा',
    'auth.branchPlaceholder': 'उदा. मुख्य शाखा',
    'auth.rememberMe': 'मला लक्षात ठेवा',
    'auth.forgotPassword': 'पासवर्ड विसरलात?',
    'auth.createBtn': 'साइन इन',
    'auth.needAccount': 'विद्यमान प्रशासक खाते वापरा',
    'auth.haveAccount': 'प्रशासक प्रवेश आवश्यक',
    'auth.helperText': 'usr-a001, usr-41033 किंवा usr-31633 सारखा विद्यमान Admin ID आणि त्याचा पासवर्ड वापरा.',

    // Farmers Page
    'farmers.title': 'शेतकरी निरीक्षण',
    'farmers.subtitle': 'सर्व केंद्रांवरील शेतकऱ्यांची माहिती व्यवस्थापित करा आणि पहा',
    'farmers.searchPlaceholder': 'नाव, आयडी, मोबाइल, गाव शोधा...',
    'farmers.allStatuses': 'सर्व स्थिती',
    'farmers.active': 'सक्रिय',
    'farmers.inactive': 'निष्क्रिय',
    'farmers.total': 'एकूण',
    'farmers.farmers': 'शेतकरी',
    'farmers.colId': 'शेतकरी आयडी',
    'farmers.colName': 'शेतकऱ्याचे नाव',
    'farmers.colMobile': 'मोबाइल',
    'farmers.colVillage': 'गाव',
    'farmers.colBookings': 'बुकिंग',
    'farmers.colStatus': 'स्थिती',
    'farmers.profile': 'शेतकरी प्रोफाइल',
    'farmers.tabInfo': 'माहिती',
    'farmers.tabBookings': 'बुकिंग इतिहास',
    'farmers.tabProcurements': 'खरेदी',
    'farmers.tabPayments': 'भुगतान',
    'farmers.farmerId': 'शेतकरी आयडी',
    'farmers.mobileNumber': 'मोबाइल नंबर',
    'farmers.aadhaar': 'आधार',
    'farmers.locationDetails': 'स्थान तपशील',
    'farmers.village': 'गाव',
    'farmers.talukaDistrict': 'तालुका / जिल्हा',
    'farmers.registrationDate': 'नोंदणी तारीख',
    'farmers.bookingId': 'बुकिंग आयडी',
    'farmers.centre': 'केंद्र',
    'farmers.date': 'तारीख',
    'farmers.time': 'वेळ',
    'farmers.crop': 'पीक',
    'farmers.id': 'आयडी',
    'farmers.qty': 'प्रमाण',
    'farmers.amount': 'रक्कम (₹)',
    'farmers.refId': 'संदर्भ आयडी',
    'farmers.procId': 'खरेदी आयडी',

    // Procurement Page
    'procurement.title': 'खरेदी निरीक्षण',
    'procurement.subtitle': 'सर्व सक्रिय केंद्रांवरील पीक खरेदीचा मागोवा घ्या',
    'procurement.allCentres': 'सर्व केंद्रे',
    'procurement.allCrops': 'सर्व पिके',
    'procurement.allStatuses': 'सर्व स्थिती',
    'procurement.completed': 'पूर्ण',
    'procurement.processing': 'प्रक्रियाधीन',
    'procurement.pending': 'प्रलंबित',
    'procurement.exportData': 'डेटा निर्यात',
    'procurement.colId': 'खरेदी आयडी',
    'procurement.colDate': 'तारीख',
    'procurement.colCentre': 'केंद्र',
    'procurement.colFarmer': 'शेतकरी',
    'procurement.colCrop': 'पीक',
    'procurement.colQty': 'प्रमाण',
    'procurement.colGrade': 'श्रेणी',
    'procurement.colAmount': 'रक्कम',
    'procurement.colStatus': 'स्थिती',

    // Payments Page
    'payments.title': 'भुगतान निरीक्षण',
    'payments.subtitle': 'प्रोटोटाइपसाठी सिम्युलेटेड भुगतान स्थितीचा मागोवा घ्या',
    'payments.totalAmount': 'एकूण रक्कम',
    'payments.completedPayments': 'पूर्ण भुगतान',
    'payments.pendingPayments': 'प्रलंबित भुगतान',
    'payments.allCentres': 'सर्व केंद्रे',
    'payments.allStatuses': 'सर्व स्थिती',
    'payments.completed': 'पूर्ण',
    'payments.pending': 'प्रलंबित',
    'payments.failed': 'अयशस्वी',
    'payments.colRefId': 'भुगतान संदर्भ आयडी',
    'payments.colFarmer': 'शेतकरी',
    'payments.colProcId': 'खरेदी आयडी',
    'payments.colCentre': 'केंद्र',
    'payments.colAmount': 'रक्कम',
    'payments.colMethod': 'पद्धत',
    'payments.colDate': 'तारीख',
    'payments.colStatus': 'स्थिती',

    // Centres & Slots
    'centres.title': 'केंद्रे, स्लॉट आणि अधिकारी',
    'centres.subtitle': 'खरेदी स्थाने, वेळ क्षमता आणि नियुक्त कर्मचारी व्यवस्थापित करा',
    'centres.tabCentres': 'केंद्रे',
    'centres.tabSlots': 'स्लॉट आणि क्षमता कॉन्फिगरेशन',
    'centres.tabOfficers': 'अधिकारी',
    'centres.addCentre': 'केंद्र जोडा',
    'centres.createSlots': 'स्लॉट तयार करा',
    'centres.assignOfficer': 'अधिकारी नियुक्त करा',
    'centres.selectCentre': 'केंद्र निवडा',
    'centres.filterByCentre': 'केंद्राद्वारे फिल्टर करा',
    'centres.colCentreId': 'केंद्र आयडी',
    'centres.colName': 'केंद्राचे नाव',
    'centres.colTaluka': 'तालुका',
    'centres.colCapacity': 'एकूण क्षमता',
    'centres.colCurrentLoad': 'सध्याचा भार',
    'centres.colStatus': 'स्थिती',
    'centres.colActions': 'कृती',
    'centres.colDate': 'तारीख',
    'centres.colTimeSlot': 'वेळ स्लॉट',
    'centres.colSlotCapacity': 'क्षमता',
    'centres.colBooked': 'बुक केलेले',
    'centres.colRemaining': 'उर्वरित',
    'centres.colOfficerId': 'अधिकारी आयडी',
    'centres.colOfficerName': 'नाव',
    'centres.colRole': 'भूमिका',
    'centres.colMobile': 'मोबाइल',
    'centres.colAssignedCentre': 'नियुक्त केंद्र',
    'centres.officerNote': 'टीप: अधिकारी त्यांच्या समर्पित ॲप्लिकेशनवरून रांगा व्यवस्थापित करतात. प्रशासक त्यांना येथे पाहू आणि नियुक्त करू शकतात.',
    'centres.modalAddCentre': 'नवीन केंद्र जोडा',
    'centres.modalEditCentre': 'खरेदी केंद्र संपादित करा',
    'centres.modalConfigSlots': 'स्लॉट आणि क्षमता कॉन्फिगर करा',
    'centres.btnCancel': 'रद्द करा',
    'centres.btnSaveCentre': 'केंद्र जतन करा',
    'centres.btnGenerateSlots': 'स्लॉट तयार करा',
    'centres.lblCentreName': 'केंद्राचे नाव',
    'centres.lblTaluka': 'तालुका',
    'centres.lblDistrict': 'जिल्हा',
    'centres.lblAddress': 'पत्ता',
    'centres.lblBaseCapacity': 'मूळ क्षमता (प्रति तास)',
    'centres.lblStatus': 'स्थिती',
    'centres.lblStartDate': 'सुरुवातीची तारीख',
    'centres.lblEndDate': 'शेवटची तारीख',
    'centres.lblTimeRange': 'वेळ श्रेणी',
    'centres.lblSlotDuration': 'स्लॉट कालावधी (मिनिटे)',
    'centres.lblCapacityPerSlot': 'क्षमता प्रति स्लॉट',
    'centres.placeholderCentreName': 'उदा., कोपरगाव एपीएमसी केंद्र',
    'centres.capacityNote': 'सिस्टम या कॉन्फिगर केलेल्या क्षमतेच्या पलीकडे बुकिंग कठोरपणे प्रतिबंधित करेल.',
    'centres.min30': '३० मिनिटे',
    'centres.min60': '६० मिनिटे (१ तास)',
    'centres.to': 'ते',

    // queue
    'queue.title': 'थेट रांग निरीक्षण',
    'queue.subtitle': 'सर्व खरेदी केंद्रांमधील रिअल-टाइम रांगांचे केंद्रीकृत दृश्य',
    'queue.liveUpdates': 'थेट अद्यतने सक्रिय',
    'queue.centreId': 'केंद्र आयडी',
    'queue.currentToken': 'वर्तमान टोकन',
    'queue.serving': 'सेवा देत आहे',
    'queue.waitingFarmers': 'प्रतीक्षेत असलेले शेतकरी',
    'queue.highLoadAlert': 'उच्च भार सतर्कता',
    'queue.estWaitTime': 'अंदाजित प्रतीक्षा वेळ',
    'queue.tokensCompleted': 'टोकन पूर्ण झाले',

    // analytics
    'analytics.title': 'सिस्टम विश्लेषण आणि अंदाज',
    'analytics.subtitle': 'डेटा-चालित अंतर्दृष्टी, ट्रेंड आणि AI/ML अंदाज',
    'analytics.aiPredictions': 'AI/ML अंदाज',
    'analytics.predicted': 'अंदाज वर्तवला',
    'analytics.expectedCrowd': 'अपेक्षित गर्दीची पातळी (आज)',
    'analytics.avgEstWait': 'सरासरी अंदाजित प्रतीक्षा वेळ',
    'analytics.peakWindow': 'पीक प्रोसेसिंग विंडो',
    'analytics.expectedNoShow': 'अपेक्षित नो-शो दर',
    'analytics.confidence': 'आत्मविश्वास',
    'analytics.tabFarmer': 'शेतकरी विश्लेषण',
    'analytics.tabProcurement': 'खरेदी',
    'analytics.tabQueue': 'रांग आणि केंद्रे',
    'analytics.farmerReg': 'शेतकरी नोंदणी (२०२५-२०२६)',
    'analytics.villageDist': 'गाव वितरण',
    'analytics.dailyVol': 'दैनिक खरेदी खंड',
    'analytics.cropDist': 'पीक वितरण',
    'analytics.avgWait': 'दिवसभर सरासरी प्रतीक्षा वेळ',
    'analytics.centreCap': 'केंद्र क्षमता वापर (%)',
    'analytics.aiRecommendations': 'AI सिस्टम शिफारसी',
    'analytics.predictedLoad': 'अंदाजित भार',
    'analytics.lblRegistrations': 'नोंदणी',
    'analytics.lblFarmers': 'शेतकरी',
    'analytics.lblProcurementsCompleted': 'खरेदी पूर्ण झाली',
    'analytics.lblWaitTime': 'प्रतीक्षा वेळ (मिनिटे)',
    'analytics.lblUtilization': 'वापर %',

    // reports
    'reports.title': 'अहवाल आणि निर्यात',
    'reports.subtitle': 'मासिक सारांश तयार करा आणि बाह्य वापरासाठी डेटा निर्यात करा',
    'reports.monthlySummary': 'मासिक सारांश अहवाल',
    'reports.exportPdf': 'PDF निर्यात करा',
    'reports.exportCsv': 'CSV निर्यात करा',
    'reports.totalFarmers': 'एकूण शेतकरी सेवा दिली',
    'reports.totalProcurement': 'एकूण खरेदी',
    'reports.totalAmount': 'एकूण रक्कम',
    'reports.avgWaitTime': 'सरासरी प्रतीक्षा वेळ',
    'reports.centrePerformance': 'केंद्र कामगिरी तपशील',
    'reports.colName': 'केंद्राचे नाव',
    'reports.colCapacity': 'क्षमता (प्रति तास)',
    'reports.colUtilization': 'सरासरी वापर',
    'reports.colThroughput': 'शेतकरी सेवा दिली',
    'reports.colWaitTime': 'सरासरी प्रतीक्षा वेळ',
  },
  hi: {
    // Sidebar
    'nav.dashboard': 'डैशबोर्ड',
    'nav.queue': 'कतार निगरानी',
    'nav.farmers': 'किसान',
    'nav.procurement': 'खरीद',
    'nav.payments': 'भुगतान',
    'nav.centres': 'केंद्र और स्लॉट',
    'nav.analytics': 'विश्लेषण',
    'nav.reports': 'रिपोर्ट',
    'nav.operations': 'संचालन',
    'nav.collapse': 'संपीड़ित करें',

    // Header & Search
    'header.search': 'किसान, टोकन खोजें...',
    'header.settings': 'सेटिंग्स',
    'header.notifications': 'सूचनाएं',
    'header.logout': 'लॉगआउट',

    // Dashboard
    'dashboard.title': 'संचालन डैशबोर्ड',
    'dashboard.subtitle': 'खरीद-केंद्र गतिविधि का रीयल-टाइम अवलोकन',
    'dashboard.overview': 'सिस्टम अवलोकन',
    'dashboard.overview.subtitle': 'कृषीदर्पण रीयल-टाइम संचालन मेट्रिक्स',
    'dashboard.totalFarmers': 'कुल किसान आज',
    'dashboard.waiting': 'प्रतीक्षा में',
    'dashboard.serving': 'वर्तमान में सेवा दे रहे हैं',
    'dashboard.completed': 'पूर्ण खरीद',
    'dashboard.pendingPayments': 'लंबित भुगतान',
    'dashboard.totalAmount': 'कुल राशि (₹)',
    'dashboard.capacityUtilization': 'केंद्र क्षमता उपयोग',
    'dashboard.liveQueue': 'लाइव कतार अवलोकन',
    'dashboard.live': 'लाइव',
    'dashboard.currentToken': 'वर्तमान टोकन',
    'dashboard.centre': 'केंद्र',
    'dashboard.waitingCol': 'प्रतीक्षा में',
    'dashboard.estWait': 'अनुमानित प्रतीक्षा',
    'dashboard.quickActions': 'त्वरित क्रियाएं',

    // Button Labels
    'btn.login': 'लॉगइन',
    'btn.logout': 'लॉगआउट',
    'btn.signup': 'साइन अप',
    'btn.back': '← भूमिका चयन पर वापस जाएं',
    'btn.search': 'खोजें',
    'btn.filter': 'फ़िल्टर',
    'btn.export': 'निर्यात',
    'btn.manageCentres': 'केंद्रों को प्रबंधित करें',
    'btn.manageCentres.desc': 'खरीद केंद्र जोड़ें या संपादित करें',
    'btn.manageSlots': 'स्लॉट प्रबंधित करें',
    'btn.manageSlots.desc': 'क्षमता और तारीख कॉन्फ़िगर करें',
    'btn.queueMonitor': 'कतार मॉनिटर',
    'btn.queueMonitor.desc': 'रीयल-टाइम टोकन स्थिति देखें',
    'btn.viewAnalytics': 'विश्लेषण देखें',
    'btn.viewAnalytics.desc': 'AI भविष्यवाणी और रुझान देखें',

    // Status Labels
    'status.active': 'सक्रिय',
    'status.inactive': 'निष्क्रिय',
    'status.processing': 'प्रक्रिया में',
    'status.completed': 'पूर्ण',
    'status.pending': 'लंबित',
    'status.failed': 'विफल',

    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.search': 'खोजें...',
    'common.filter': 'फ़िल्टर',
    'common.language': 'भाषा',
    'common.english': 'English',
    'common.marathi': 'मराठी',
    'common.hindi': 'हिन्दी',

    // Auth
    'auth.adminLogin': 'एडमिन लॉगइन',
    'auth.createAccount': 'एडमिन खाता बनाएं',
    'auth.signInDesc': 'सिस्टम संचालन प्रबंधित करने के लिए साइन इन करें',
    'auth.signUpDesc': 'मौजूदा प्रशासक खाते से साइन इन करें',
    'auth.username': 'उपयोगकर्ता नाम / एडमिन नाम',
    'auth.usernamePlaceholder': 'अपना एडमिन नाम दर्ज करें',
    'auth.password': 'पासवर्ड',
    'auth.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
    'auth.adminId': 'एडमिन आईडी',
    'auth.adminIdPlaceholder': 'उदा. ADM-2024-001',
    'auth.branch': 'शाखा',
    'auth.branchPlaceholder': 'उदा. मुख्य शाखा',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.createBtn': 'साइन इन',
    'auth.needAccount': 'मौजूदा प्रशासक खाता उपयोग करें',
    'auth.haveAccount': 'प्रशासक एक्सेस आवश्यक है',
    'auth.helperText': 'usr-a001, usr-41033, या usr-31633 जैसे मौजूदा Admin ID और उसका पासवर्ड उपयोग करें।',

    // Farmers Page
    'farmers.title': 'किसान निगरानी',
    'farmers.subtitle': 'सभी केंद्रों पर किसानों की जानकारी प्रबंधित करें और देखें',
    'farmers.searchPlaceholder': 'नाम, आईडी, मोबाइल, गांव खोजें...',
    'farmers.allStatuses': 'सभी स्थितियां',
    'farmers.active': 'सक्रिय',
    'farmers.inactive': 'निष्क्रिय',
    'farmers.total': 'कुल',
    'farmers.farmers': 'किसान',
    'farmers.colId': 'किसान आईडी',
    'farmers.colName': 'किसान का नाम',
    'farmers.colMobile': 'मोबाइल',
    'farmers.colVillage': 'गांव',
    'farmers.colBookings': 'बुकिंग',
    'farmers.colStatus': 'स्थिति',
    'farmers.profile': 'किसान प्रोफाइल',
    'farmers.tabInfo': 'जानकारी',
    'farmers.tabBookings': 'बुकिंग इतिहास',
    'farmers.tabProcurements': 'खरीद',
    'farmers.tabPayments': 'भुगतान',
    'farmers.farmerId': 'किसान आईडी',
    'farmers.mobileNumber': 'मोबाइल नंबर',
    'farmers.aadhaar': 'आधार',
    'farmers.locationDetails': 'स्थान विवरण',
    'farmers.village': 'गांव',
    'farmers.talukaDistrict': 'तालुका / जिला',
    'farmers.registrationDate': 'पंजीकरण तिथि',
    'farmers.bookingId': 'बुकिंग आईडी',
    'farmers.centre': 'केंद्र',
    'farmers.date': 'तारीख',
    'farmers.time': 'समय',
    'farmers.crop': 'फसल',
    'farmers.id': 'आईडी',
    'farmers.qty': 'मात्रा',
    'farmers.amount': 'राशि (₹)',
    'farmers.refId': 'संदर्भ आईडी',
    'farmers.procId': 'खरीद आईडी',

    // Procurement Page
    'procurement.title': 'खरीद निगरानी',
    'procurement.subtitle': 'सभी सक्रिय केंद्रों पर फसल खरीद का ट्रैक करें',
    'procurement.allCentres': 'सभी केंद्र',
    'procurement.allCrops': 'सभी फसलें',
    'procurement.allStatuses': 'सभी स्थितियां',
    'procurement.completed': 'पूर्ण',
    'procurement.processing': 'प्रक्रिया में',
    'procurement.pending': 'लंबित',
    'procurement.exportData': 'डेटा निर्यात',
    'procurement.colId': 'खरीद आईडी',
    'procurement.colDate': 'तारीख',
    'procurement.colCentre': 'केंद्र',
    'procurement.colFarmer': 'किसान',
    'procurement.colCrop': 'फसल',
    'procurement.colQty': 'मात्रा',
    'procurement.colGrade': 'ग्रेड',
    'procurement.colAmount': 'राशि',
    'procurement.colStatus': 'स्थिति',

    // Payments Page
    'payments.title': 'भुगतान निगरानी',
    'payments.subtitle': 'प्रोटोटाइप के लिए सिम्युलेटेड भुगतान स्थिति ट्रैक करें',
    'payments.totalAmount': 'कुल राशि',
    'payments.completedPayments': 'पूर्ण भुगतान',
    'payments.pendingPayments': 'लंबित भुगतान',
    'payments.allCentres': 'सभी केंद्र',
    'payments.allStatuses': 'सभी स्थितियां',
    'payments.completed': 'पूर्ण',
    'payments.pending': 'लंबित',
    'payments.failed': 'विफल',
    'payments.colRefId': 'भुगतान संदर्भ आईडी',
    'payments.colFarmer': 'किसान',
    'payments.colProcId': 'खरीद आईडी',
    'payments.colCentre': 'केंद्र',
    'payments.colAmount': 'राशि',
    'payments.colMethod': 'तरीका',
    'payments.colDate': 'तारीख',
    'payments.colStatus': 'स्थिति',

    // Centres & Slots
    'centres.title': 'केंद्र, स्लॉट और अधिकारी',
    'centres.subtitle': 'खरीद स्थान, समय क्षमता और नियुक्त कर्मियों का प्रबंधन करें',
    'centres.tabCentres': 'केंद्र',
    'centres.tabSlots': 'स्लॉट और क्षमता कॉन्फ़िगरेशन',
    'centres.tabOfficers': 'अधिकारी',
    'centres.addCentre': 'केंद्र जोड़ें',
    'centres.createSlots': 'स्लॉट बनाएं',
    'centres.assignOfficer': 'अधिकारी नियुक्त करें',
    'centres.selectCentre': 'केंद्र चुनें',
    'centres.filterByCentre': 'केंद्र द्वारा फ़िल्टर करें',
    'centres.colCentreId': 'केंद्र आईडी',
    'centres.colName': 'केंद्र का नाम',
    'centres.colTaluka': 'तालुका',
    'centres.colCapacity': 'कुल क्षमता',
    'centres.colCurrentLoad': 'वर्तमान भार',
    'centres.colStatus': 'स्थिति',
    'centres.colActions': 'क्रियाएँ',
    'centres.colDate': 'तारीख',
    'centres.colTimeSlot': 'समय स्लॉट',
    'centres.colSlotCapacity': 'क्षमता',
    'centres.colBooked': 'बुक किया गया',
    'centres.colRemaining': 'शेष',
    'centres.colOfficerId': 'अधिकारी आईडी',
    'centres.colOfficerName': 'नाम',
    'centres.colRole': 'भूमिका',
    'centres.colMobile': 'मोबाइल',
    'centres.colAssignedCentre': 'नियुक्त केंद्र',
    'centres.officerNote': 'नोट: अधिकारी अपने समर्पित एप्लिकेशन से कतारों का प्रबंधन करते हैं। व्यवस्थापक उन्हें यहां देख और नियुक्त कर सकते हैं।',
    'centres.modalAddCentre': 'नया केंद्र जोड़ें',
    'centres.modalEditCentre': 'खरीद केंद्र संपादित करें',
    'centres.modalConfigSlots': 'स्लॉट और क्षमता कॉन्फ़िगर करें',
    'centres.btnCancel': 'रद्द करें',
    'centres.btnSaveCentre': 'केंद्र सहेजें',
    'centres.btnGenerateSlots': 'स्लॉट बनाएं',
    'centres.lblCentreName': 'केंद्र का नाम',
    'centres.lblTaluka': 'तालुका',
    'centres.lblDistrict': 'जिला',
    'centres.lblAddress': 'पता',
    'centres.lblBaseCapacity': 'मूल क्षमता (प्रति घंटे)',
    'centres.lblStatus': 'स्थिति',
    'centres.lblStartDate': 'प्रारंभ तिथि',
    'centres.lblEndDate': 'अंतिम तिथि',
    'centres.lblTimeRange': 'समय सीमा',
    'centres.lblSlotDuration': 'स्लॉट अवधि (मिनट)',
    'centres.lblCapacityPerSlot': 'क्षमता प्रति स्लॉट',
    'centres.placeholderCentreName': 'उदा., कोपरगांव एपीएमसी केंद्र',
    'centres.capacityNote': 'सिस्टम इस कॉन्फ़िगर की गई क्षमता से अधिक बुकिंग को सख्ती से रोकेगा।',
    'centres.min30': '३० मिनट',
    'centres.min60': '६० मिनट (१ घंटा)',
    'centres.to': 'से',

    // queue
    'queue.title': 'लाइव कतार निगरानी',
    'queue.subtitle': 'सभी खरीद केंद्रों में रीयल-टाइम कतारों का केंद्रीकृत दृश्य',
    'queue.liveUpdates': 'लाइव अपडेट सक्रिय',
    'queue.centreId': 'केंद्र आईडी',
    'queue.currentToken': 'वर्तमान टोकन',
    'queue.serving': 'सेवा दे रहे हैं',
    'queue.waitingFarmers': 'प्रतीक्षारत किसान',
    'queue.highLoadAlert': 'उच्च भार चेतावनी',
    'queue.estWaitTime': 'अनुमानित प्रतीक्षा समय',
    'queue.tokensCompleted': 'टोकन पूर्ण हुए',

    // analytics
    'analytics.title': 'सिस्टम विश्लेषण और भविष्यवाणियां',
    'analytics.subtitle': 'डेटा-संचालित अंतर्दृष्टि, रुझान और एआई/एमएल भविष्यवाणियां',
    'analytics.aiPredictions': 'एआई/एमएल भविष्यवाणियां',
    'analytics.predicted': 'भविष्यवाणी की गई',
    'analytics.expectedCrowd': 'अपेक्षित भीड़ स्तर (आज)',
    'analytics.avgEstWait': 'औसत अनुमानित प्रतीक्षा समय',
    'analytics.peakWindow': 'पीक प्रोसेसिंग विंडो',
    'analytics.expectedNoShow': 'अपेक्षित नो-शो दर',
    'analytics.confidence': 'विश्वास',
    'analytics.tabFarmer': 'किसान विश्लेषण',
    'analytics.tabProcurement': 'खरीद',
    'analytics.tabQueue': 'कतार और केंद्र',
    'analytics.farmerReg': 'किसान पंजीकरण (२०२५-२०२६)',
    'analytics.villageDist': 'गांव वितरण',
    'analytics.dailyVol': 'दैनिक खरीद मात्रा',
    'analytics.cropDist': 'फसल वितरण',
    'analytics.avgWait': 'दिन भर औसत प्रतीक्षा समय',
    'analytics.centreCap': 'केंद्र क्षमता उपयोग (%)',
    'analytics.aiRecommendations': 'एआई सिस्टम सिफारिशें',
    'analytics.predictedLoad': 'अनुमानित भार',
    'analytics.lblRegistrations': 'पंजीकरण',
    'analytics.lblFarmers': 'किसान',
    'analytics.lblProcurementsCompleted': 'खरीद पूरी हुई',
    'analytics.lblWaitTime': 'प्रतीक्षा समय (मिनट)',
    'analytics.lblUtilization': 'उपयोग %',

    // reports
    'reports.title': 'रिपोर्ट और निर्यात',
    'reports.subtitle': 'मासिक सारांश बनाएं और बाहरी उपयोग के लिए डेटा निर्यात करें',
    'reports.monthlySummary': 'मासिक सारांश रिपोर्ट',
    'reports.exportPdf': 'PDF निर्यात करें',
    'reports.exportCsv': 'CSV निर्यात करें',
    'reports.totalFarmers': 'कुल किसान सेवा दी गई',
    'reports.totalProcurement': 'कुल खरीद',
    'reports.totalAmount': 'कुल राशि',
    'reports.avgWaitTime': 'औसत प्रतीक्षा समय',
    'reports.centrePerformance': 'केंद्र प्रदर्शन विवरण',
    'reports.colName': 'केंद्र का नाम',
    'reports.colCapacity': 'क्षमता (प्रति घंटे)',
    'reports.colUtilization': 'औसत उपयोग',
    'reports.colThroughput': 'किसान सेवा दी गई',
    'reports.colWaitTime': 'औसत प्रतीक्षा समय',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // Load from localStorage on mount
    if (typeof window !== 'undefined') {
      return localStorage.getItem('QueueKisan_language') || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    // Save to localStorage whenever language changes
    localStorage.setItem('QueueKisan_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}

export default LanguageContext;
